AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/
Metrics/LineLength:
    Max: 100
    Exclude:
      - 'app/uploaders/avatar_uploader.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
